### ISSUE TITLE
Question: tiled quantized mesh is 700 MB while traditional terrain is 40MB

### ISSUE THREAD

**Issue by AbegNext** [tum-gis/cesium-terrain-builder-docker#1] opened 2018-11-04 20:13 UTC
Hi,

I think this is a great tool! I just tried it and I am wondering the following command: "ctb-tile -f Mesh -C -N  -o ./output input.tif" and it is 700MB, while if I tried the original terrain it is 40 mb using "ctb-tile -C -N -o ./output  input.tif". I thought quantized mesh would produce a lighter tiled model. Am I doing something wrong? Thanks

**Comment by BWibo** [comment] 2018-11-04 23:55
I just tried to reproduce this with a test dataset. As listed below, the output of both runs is of equal size.
Get in contact with the developers of [CTB](https://github.com/geo-data/cesium-terrain-builder) and [Quantized Mesh](https://github.com/geo-data/cesium-terrain-builder/pull/64) support. If possible, share the input dataset.
```
root@8effdb02df49:/data/augsburg# l
augsburg/  hmap/  new/  quantized/  GEOTIFF.tif*  tiles.vrt
root@8effdb02df49:/data/augsburg# rm -r hmap/* quantized/*
root@8effdb02df49:/data/augsburg# ctb-tile -N -C -f Mesh -o quantized/ GEOTIFF.tif
0...10...20...30...40...50...60...70...80...90...100 - done.
0root@8effdb02df49:/data/augsburg# ctb-tile -N -C -o hmap/ GEOTIFF.tif
0...10...20...30...40...50...60...70...80...90...100 - done.
0root@8effdb02df49:/data/augsburg# du -hs hmap/ quantized/
34M     hmap/
34M     quantized/
```
Closing, as this seems to be related to CTB and not the content of this repo. Feel free to re-open if necessary.

**Closed as completed by BWibo** 2018-11-04 23:55 UTC
